version: '3.8'

services:
  dock_productos:
    image: volkyodha/dock_productos:latest
    ports:
      - "3002:3002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/elysium

  dock_clientes:
    image: volkyodha/dock_clientes:latest
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/elysium

  dock_visual:
    image: volkyodha/dock_visual:latest
    ports:
      - "3003:3003"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/elysium

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
